### ISSUE TITLE
Not compatible with Ruby 2.3

### ISSUE THREAD

**Issue by ojeno** [boborbt/priority_queue_cxx#2]
It seems this gem is not working anymore with Ruby 2.3.

Using the standard script:

`require 'priority_queue_cxx'\n
q = FastContainers::PriorityQueue.new(:max)
q.push("largest", 10)
q.push("smallest", 5)
q.top      # =>  "largest"
q.top_key  # => 10
q.pop`

Results in:

`C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
: cannot load such file -- priority_queue_cxx (LoadError)
        from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55
:in `require'
        from test.rb:2:in <main>

**Comment by boborbt** [comment]
Hi ojeno. Sorry for the late answer, I did not see the notification until today. I'm looking at the problem right now.

Thanks for the feedback!

Roberto

**Comment by boborbt** [comment]
Hi ojeno. Everything seems working fine here.

perhaps you are requiring the wrong object? Note that, as the documentation shows, you need to require `fc` not `priority_queue_cxx`.

The following example works fine in my environment:

```ruby
require 'fc'
q = FastContainers::PriorityQueue.new(:max)
q.push("largest", 10)
q.push("smallest", 5)
puts q.top      # =>  "largest"
puts q.top_key  # => 10
puts q.pop
```

**Comment by ojeno** [comment]
Thanks for your response. Indeed, I required the wrong string. It works now.
