### ISSUE TITLE
second_best_key does not work correctly for min queue

### ISSUE THREAD

**Issue by surenderk2009** [boborbt/priority_queue_cxx#8]
second_best_key is not returning correct value for min queue but working fine for max queue. 
Scenario: Min queue.
Elements (object, priority) :
"a",2
"b",2
"c",3
Top is "a" with priority 2. second_best_key is returning 3. If we pop "a" then "b" is becoming top which has priority 2. If we go by this logic, shouldn't second_best_key return 2 as b was second best key after a? What do you exactly mean when you say second best key in a priority queue? Isn't it the next best candidate to become top if current top is popped? 
When I created a max queue with similar scenario two elements with same priority out of which one is top and a third with lower priority (a with 3, b with 3 and c with 2 where a is top), then second (b) is returned as output of second_best_key.

**Comment by boborbt** [comment]
You are right, there was a bug in the implementation.
I just published a new version of the gem and pushed it to rubygems. Now it should work properly.

Thanks for the feedback.
